/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.*;
/**
 *
 * @author Ali Asaf
 */
public class AnaEkran extends javax.swing.JFrame {
 Color old;
    /**
     * Creates new form NumberAdditionForm
     */
    public AnaEkran() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDevam = new javax.swing.JButton();
        lblSabıkaKaydıYazısı = new javax.swing.JLabel();
        KullanıcıGiris = new javax.swing.JTextField();
        lblKullanıcıGirisiYazısı = new javax.swing.JLabel();
        KullanıcıSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        btnDevam.setText("Devam");
        btnDevam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnDevam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevamMouseExited(evt);
            }
        });
        btnDevam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevamActionPerformed(evt);
            }
        });

        lblSabıkaKaydıYazısı.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSabıkaKaydıYazısı.setText("Sabıka Kaydı Sorgulama Sistemi");
        lblSabıkaKaydıYazısı.setToolTipText("");

        KullanıcıGiris.setText("ör:Asaf123");

        lblKullanıcıGirisiYazısı.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblKullanıcıGirisiYazısı.setText("Kullanıcı Girişi :");
        lblKullanıcıGirisiYazısı.setToolTipText("");

        KullanıcıSifre.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblSabıkaKaydıYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(KullanıcıSifre)
                    .addComponent(lblKullanıcıGirisiYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(KullanıcıGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDevam, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSabıkaKaydıYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKullanıcıGirisiYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KullanıcıGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KullanıcıSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnDevam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        btnDevam.getAccessibleContext().setAccessibleName("btnDevam");
        lblSabıkaKaydıYazısı.getAccessibleContext().setAccessibleName("sabıkaLabel");
        KullanıcıGiris.getAccessibleContext().setAccessibleName("txtUser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Panel1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevamActionPerformed
        
        VeriTabani vt=new VeriTabani();
        String kullanıcı=KullanıcıGiris.getText().toString();
        String sifre=KullanıcıSifre.getText().toString();
        
        
        kisiBulunamadı hata=new kisiBulunamadı();
        
        String gelenKullanıcı=vt.kullanici(kullanıcı,sifre);
        //System.out.println(gelenKullanıcı);
        if(gelenKullanıcı!=null){
          //  System.out.println("puf");
            if(gelenKullanıcı.compareTo("Polis")==0){
                PolisEkranı polisE=new PolisEkranı(KullanıcıGiris.getText().toString());
                polisE.setVisible(true);
            }else{
                MemurEkranı memurE=new MemurEkranı(KullanıcıGiris.getText().toString());
                memurE.setVisible(true);}
        }else
        hata.setVisible(true);    
        
        
        
        /*PolisEkranı ekran=new PolisEkranı(KullanıcıGiris.getText().toString());
        MemurEkranı ekran2=new MemurEkranı(KullanıcıGiris.getText().toString());
        if(KullanıcıGiris.getText().toString().compareTo("")==0||KullanıcıSifre.getText().toString().compareTo("")==0){
            kisiBulunamadı hata=new kisiBulunamadı();
            hata.setVisible(true);
        }else
        ekran2.setVisible(true);*/
/*        else if(KullanıcıGiris.getText().toString().charAt(0)){
                
                }
        Burada gelen kullanıcı adının ilk harfine göre hangi veritabanında arandığına karar verilecek varsa giriş yapılacak yoksa giremeyecek
        m ise memur , p ise polis database ine bakılacak
        
        
        */
        //Burada yine alınan kullanıcının veritabanında olup olmadığını kontrol edicez.
        
        
    }//GEN-LAST:event_btnDevamActionPerformed

    private void btnDevamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevamMouseEntered
      old=btnDevam.getForeground();  
      btnDevam.setForeground(Color.red);
    }//GEN-LAST:event_btnDevamMouseEntered

    private void btnDevamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevamMouseExited
        btnDevam.setForeground(old);// TODO add your handling code here:
    }//GEN-LAST:event_btnDevamMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        AnaEkran form=new AnaEkran();
        //form.setVisible(true);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KullanıcıGiris;
    private javax.swing.JPasswordField KullanıcıSifre;
    private javax.swing.JButton btnDevam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKullanıcıGirisiYazısı;
    private javax.swing.JLabel lblSabıkaKaydıYazısı;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconResmi.png"))); //To change body of generated methods, choose Tools | Templates.
    }
}
