/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Ali Asaf
 */
public class MemurEkranıSorgu extends javax.swing.JFrame {
    public String gelenTc;
    public String gelenAd;
    Color old;
    /**
     * Creates new form MemurEkranıSorgu
     */
    public MemurEkranıSorgu(){
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }
    
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconResmi.png"))); //To change body of generated methods, choose Tools | Templates.
    }
    
    public MemurEkranıSorgu(String tc) {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.gelenTc=tc;
        lblTcInput.setText(gelenTc);
        VeriTabani Tt=new VeriTabani();
        Insan a=Tt.goruntule(tc);
        this.gelenAd=a.İsim+" "+a.Soyİsim;
        lblGelenAd.setText(gelenAd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSabıkaYazısı = new javax.swing.JLabel();
        lblSecimYapınızYazısı = new javax.swing.JLabel();
        btnSabıkaGoruntule = new javax.swing.JButton();
        btnSabıkaGirisiYap = new javax.swing.JButton();
        btnCezaiDurumGuncelle = new javax.swing.JButton();
        lblTCNoYazısı = new javax.swing.JLabel();
        lblTcInput = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblGelenAd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        lblSabıkaYazısı.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSabıkaYazısı.setForeground(new java.awt.Color(51, 102, 255));
        lblSabıkaYazısı.setText("Sabıka Kaydı Sorgulama Sistemi");

        lblSecimYapınızYazısı.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSecimYapınızYazısı.setForeground(new java.awt.Color(51, 102, 255));
        lblSecimYapınızYazısı.setText("Seçim Yapınız ");

        btnSabıkaGoruntule.setText("Sabıka Görüntüle");
        btnSabıkaGoruntule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnSabıkaGoruntule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSabıkaGoruntuleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSabıkaGoruntuleMouseExited(evt);
            }
        });
        btnSabıkaGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSabıkaGoruntuleActionPerformed(evt);
            }
        });

        btnSabıkaGirisiYap.setText("Sabıka Girişi Yap");
        btnSabıkaGirisiYap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnSabıkaGirisiYap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSabıkaGirisiYapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSabıkaGirisiYapMouseExited(evt);
            }
        });
        btnSabıkaGirisiYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSabıkaGirisiYapActionPerformed(evt);
            }
        });

        btnCezaiDurumGuncelle.setText("Cezai Durum Güncelle");
        btnCezaiDurumGuncelle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnCezaiDurumGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCezaiDurumGuncelleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCezaiDurumGuncelleMouseExited(evt);
            }
        });
        btnCezaiDurumGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCezaiDurumGuncelleActionPerformed(evt);
            }
        });

        lblTCNoYazısı.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTCNoYazısı.setForeground(new java.awt.Color(51, 102, 255));
        lblTCNoYazısı.setText("TC No :");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Ad-Soyad :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSabıkaGoruntule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSabıkaGirisiYap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCezaiDurumGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSecimYapınızYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblGelenAd, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTCNoYazısı)
                                .addGap(43, 43, 43)
                                .addComponent(lblTcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTCNoYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGelenAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblSecimYapınızYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSabıkaGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSabıkaGirisiYap, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCezaiDurumGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        btnSabıkaGoruntule.getAccessibleContext().setAccessibleName("btnSabıkaGoruntule");
        btnSabıkaGirisiYap.getAccessibleContext().setAccessibleName("btnSabıkaGiris");
        btnCezaiDurumGuncelle.getAccessibleContext().setAccessibleName("btnCezaiDurum");
        lblTCNoYazısı.getAccessibleContext().setAccessibleName("lblTcBaslık");
        lblTcInput.getAccessibleContext().setAccessibleName("lblTcGirisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("panelMemurSorgu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSabıkaGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSabıkaGoruntuleActionPerformed
        VeriTabani vt=new VeriTabani();
        
       PolisEkranıSorgu ekran=new PolisEkranıSorgu(vt.goruntule(gelenTc));
        ekran.setVisible(true);
        
       
    }//GEN-LAST:event_btnSabıkaGoruntuleActionPerformed

    private void btnSabıkaGirisiYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSabıkaGirisiYapActionPerformed
    
        VeriTabani vt=new VeriTabani();
        MemurSabıkaGirişiEkranı ekran=new MemurSabıkaGirişiEkranı(vt.goruntule(gelenTc));
        ekran.setVisible(true);
    }//GEN-LAST:event_btnSabıkaGirisiYapActionPerformed

    private void btnCezaiDurumGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCezaiDurumGuncelleActionPerformed
         VeriTabani vt=new VeriTabani();
        MemurCezaiDurumGüncelle ekran=new MemurCezaiDurumGüncelle(vt.goruntule(gelenTc));
        ekran.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnCezaiDurumGuncelleActionPerformed

    private void btnSabıkaGoruntuleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabıkaGoruntuleMouseEntered
      old=btnSabıkaGoruntule.getForeground();
      btnSabıkaGoruntule.setForeground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_btnSabıkaGoruntuleMouseEntered

    private void btnSabıkaGoruntuleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabıkaGoruntuleMouseExited
       btnSabıkaGoruntule.setForeground(old); // TODO add your handling code here:
    }//GEN-LAST:event_btnSabıkaGoruntuleMouseExited

    private void btnSabıkaGirisiYapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabıkaGirisiYapMouseEntered
      old=btnSabıkaGirisiYap.getForeground();
      btnSabıkaGirisiYap.setForeground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_btnSabıkaGirisiYapMouseEntered

    private void btnSabıkaGirisiYapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSabıkaGirisiYapMouseExited
     btnSabıkaGirisiYap.setForeground(old);   // TODO add your handling code here:
    }//GEN-LAST:event_btnSabıkaGirisiYapMouseExited

    private void btnCezaiDurumGuncelleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCezaiDurumGuncelleMouseEntered
      old=btnCezaiDurumGuncelle.getForeground();
      btnCezaiDurumGuncelle.setForeground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCezaiDurumGuncelleMouseEntered

    private void btnCezaiDurumGuncelleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCezaiDurumGuncelleMouseExited
      btnCezaiDurumGuncelle.setForeground(old);  // TODO add your handling code here:
    }//GEN-LAST:event_btnCezaiDurumGuncelleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemurEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemurEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemurEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemurEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemurEkranıSorgu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCezaiDurumGuncelle;
    private javax.swing.JButton btnSabıkaGirisiYap;
    private javax.swing.JButton btnSabıkaGoruntule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGelenAd;
    private javax.swing.JLabel lblSabıkaYazısı;
    private javax.swing.JLabel lblSecimYapınızYazısı;
    private javax.swing.JLabel lblTCNoYazısı;
    private javax.swing.JLabel lblTcInput;
    // End of variables declaration//GEN-END:variables
}
