/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import java.awt.*;
/**
 *
 * @author Ali Asaf
 */
public class MemurCezaiGüncelleTamam extends javax.swing.JFrame {
    public String eskiDurum;
    public String yeniDurum;
    Color old;
    /**
     * Creates new form MemurCezaiGüncelleTamam
     */
    public MemurCezaiGüncelleTamam() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconResmi.png"))); //To change body of generated methods, choose Tools | Templates.
    }
    
    public MemurCezaiGüncelleTamam(String eski,String yeni) {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.eskiDurum=eski;
        this.yeniDurum=yeni;
        eskiCezai.setText(this.eskiDurum);
        yeniCezaiDurum.setText(this.yeniDurum);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eskiCezai = new javax.swing.JLabel();
        lblAraYazı = new javax.swing.JLabel();
        yeniCezaiDurum = new javax.swing.JLabel();
        lblSonyazı = new javax.swing.JLabel();
        btnTamam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eskiCezai.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        eskiCezai.setText("Denetimli Serbest");

        lblAraYazı.setText("olan cezai durum");

        yeniCezaiDurum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblSonyazı.setText("olarak değiştirildi.");

        btnTamam.setText("Tamam");
        btnTamam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnTamam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTamamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTamamMouseExited(evt);
            }
        });
        btnTamam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(eskiCezai, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAraYazı)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yeniCezaiDurum, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSonyazı, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnTamam, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yeniCezaiDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eskiCezai)
                        .addComponent(lblAraYazı))
                    .addComponent(lblSonyazı))
                .addGap(41, 41, 41)
                .addComponent(btnTamam, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTamamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamamActionPerformed
      this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnTamamActionPerformed

    private void btnTamamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTamamMouseEntered
       old=btnTamam.getForeground(); 
        btnTamam.setForeground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_btnTamamMouseEntered

    private void btnTamamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTamamMouseExited
       btnTamam.setForeground(old); // TODO add your handling code here:
    }//GEN-LAST:event_btnTamamMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemurCezaiGüncelleTamam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemurCezaiGüncelleTamam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemurCezaiGüncelleTamam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemurCezaiGüncelleTamam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemurCezaiGüncelleTamam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTamam;
    private javax.swing.JLabel eskiCezai;
    private javax.swing.JLabel lblAraYazı;
    private javax.swing.JLabel lblSonyazı;
    private javax.swing.JLabel yeniCezaiDurum;
    // End of variables declaration//GEN-END:variables
}
