/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Ali Asaf
 */
public class MemurEkranı extends javax.swing.JFrame {
    public String user;
    Color old;
    /**
     * Creates new form MemurEkranı
     */
    public MemurEkranı() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }
    
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconResmi.png"))); //To change body of generated methods, choose Tools | Templates.
    }
    
     public MemurEkranı(String user) {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.user=user;
        EnterKullanıcı.setText(this.user);
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMemurEkranıPaneli = new javax.swing.JPanel();
        lblTcKimlikYazısı = new javax.swing.JLabel();
        lblSabıkaYazısı = new javax.swing.JLabel();
        txtMemurdanGelenTc = new javax.swing.JTextField();
        btnDevam = new javax.swing.JButton();
        lblKullanıcıYazısı = new javax.swing.JLabel();
        EnterKullanıcı = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        pnlMemurEkranıPaneli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        lblTcKimlikYazısı.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTcKimlikYazısı.setForeground(new java.awt.Color(51, 102, 255));
        lblTcKimlikYazısı.setText("TC Kimlik No Giriniz:");

        lblSabıkaYazısı.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSabıkaYazısı.setForeground(new java.awt.Color(51, 102, 255));
        lblSabıkaYazısı.setText("Sabıka Kaydı Sorgulama Sistemi");

        txtMemurdanGelenTc.setText("*********");

        btnDevam.setText("Devam");
        btnDevam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnDevam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevamMouseExited(evt);
            }
        });
        btnDevam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevamActionPerformed(evt);
            }
        });

        lblKullanıcıYazısı.setForeground(new java.awt.Color(51, 51, 255));
        lblKullanıcıYazısı.setText("Kullanıcı :");

        javax.swing.GroupLayout pnlMemurEkranıPaneliLayout = new javax.swing.GroupLayout(pnlMemurEkranıPaneli);
        pnlMemurEkranıPaneli.setLayout(pnlMemurEkranıPaneliLayout);
        pnlMemurEkranıPaneliLayout.setHorizontalGroup(
            pnlMemurEkranıPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemurEkranıPaneliLayout.createSequentialGroup()
                .addGroup(pnlMemurEkranıPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(pnlMemurEkranıPaneliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMemurEkranıPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDevam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMemurEkranıPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTcKimlikYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMemurdanGelenTc, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlMemurEkranıPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKullanıcıYazısı)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnterKullanıcı, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMemurEkranıPaneliLayout.setVerticalGroup(
            pnlMemurEkranıPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemurEkranıPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTcKimlikYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemurdanGelenTc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlMemurEkranıPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EnterKullanıcı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKullanıcıYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblTcKimlikYazısı.getAccessibleContext().setAccessibleName("lblTcGir");
        lblSabıkaYazısı.getAccessibleContext().setAccessibleName("lblSabıka");
        txtMemurdanGelenTc.getAccessibleContext().setAccessibleName("TcMemurBox");
        btnDevam.getAccessibleContext().setAccessibleName("btnDevamMemur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMemurEkranıPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMemurEkranıPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevamActionPerformed
        
        String gelenTc=txtMemurdanGelenTc.getText().toString();
        MemurEkranıSorgu memurEkranıac=new MemurEkranıSorgu(txtMemurdanGelenTc.getText().toString());
        kisiBulunamadı hata=new kisiBulunamadı();
        VeriTabani vt=new VeriTabani();
        Insan insan=vt.goruntule(gelenTc);
        
        if(insan!=null){
            memurEkranıac.setVisible(true);
        }else
            hata.setVisible(true);
            
    
    }//GEN-LAST:event_btnDevamActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btnDevamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevamMouseEntered
       old=btnDevam.getForeground();
       btnDevam.setForeground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_btnDevamMouseEntered

    private void btnDevamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevamMouseExited
      btnDevam.setForeground(old);  // TODO add your handling code here:
    }//GEN-LAST:event_btnDevamMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemurEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemurEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemurEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemurEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemurEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnterKullanıcı;
    private javax.swing.JButton btnDevam;
    private javax.swing.JLabel lblKullanıcıYazısı;
    private javax.swing.JLabel lblSabıkaYazısı;
    private javax.swing.JLabel lblTcKimlikYazısı;
    private javax.swing.JPanel pnlMemurEkranıPaneli;
    private javax.swing.JTextField txtMemurdanGelenTc;
    // End of variables declaration//GEN-END:variables
}
