/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Ali Asaf
 */
public class PolisEkranı extends javax.swing.JFrame {
    public String user;
    Color old;
    /**
     * Creates new form PolisEkranı
     */
    public PolisEkranı() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconResmi.png"))); //To change body of generated methods, choose Tools | Templates.
    }
    
    public PolisEkranı(String name){
        this.user=name;
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        lblUser.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSabıkaYazısı = new javax.swing.JLabel();
        lblTCKimlikYazısı = new javax.swing.JLabel();
        txtGelenTc = new javax.swing.JTextField();
        btnSorgula = new javax.swing.JButton();
        lblKullanıcıYazısı = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        lblSabıkaYazısı.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSabıkaYazısı.setForeground(new java.awt.Color(0, 153, 51));
        lblSabıkaYazısı.setText("Sabıka Kayıt Sorgulama Sistemi");

        lblTCKimlikYazısı.setFont(lblTCKimlikYazısı.getFont().deriveFont(lblTCKimlikYazısı.getFont().getStyle() | java.awt.Font.BOLD, 15));
        lblTCKimlikYazısı.setForeground(new java.awt.Color(0, 153, 0));
        lblTCKimlikYazısı.setText("TC Kimlik No:");

        txtGelenTc.setText("11 haneli numarayı giriniz");

        btnSorgula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSorgula.setText("Sorgula");
        btnSorgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSorgulaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSorgulaMouseExited(evt);
            }
        });
        btnSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorgulaActionPerformed(evt);
            }
        });

        lblKullanıcıYazısı.setForeground(new java.awt.Color(0, 153, 0));
        lblKullanıcıYazısı.setText("Kullanıcı :");

        lblUser.setName("lblUser"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTCKimlikYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtGelenTc, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKullanıcıYazısı)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTCKimlikYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGelenTc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSorgula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKullanıcıYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblSabıkaYazısı.getAccessibleContext().setAccessibleName("labelpolis");
        txtGelenTc.getAccessibleContext().setAccessibleName("tcBox");
        btnSorgula.getAccessibleContext().setAccessibleName("btnSorgula");
        lblKullanıcıYazısı.getAccessibleContext().setAccessibleName("lblKull");
        lblUser.getAccessibleContext().setAccessibleName("lblUser");
        lblUser.getAccessibleContext().setAccessibleDescription("lblUser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("panelPolis");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorgulaActionPerformed
        VeriTabani vt=new VeriTabani();
        
        String gelenTc=txtGelenTc.getText().toString();
        Insan insan=vt.goruntule(gelenTc);
        
        if(insan!=null){
            PolisEkranıSorgu ekran=new PolisEkranıSorgu(insan);
             ekran.setVisible(true);
       }else{
        kisiBulunamadı hata=new kisiBulunamadı();
        hata.setVisible(true);
    }
        }
        
    {
    }//GEN-LAST:event_btnSorgulaActionPerformed

    private void btnSorgulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSorgulaMouseEntered
        old=btnSorgula.getForeground();
        btnSorgula.setForeground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_btnSorgulaMouseEntered

    private void btnSorgulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSorgulaMouseExited
       btnSorgula.setForeground(old); // TODO add your handling code here:
    }//GEN-LAST:event_btnSorgulaMouseExited

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolisEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSorgula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKullanıcıYazısı;
    private javax.swing.JLabel lblSabıkaYazısı;
    private javax.swing.JLabel lblTCKimlikYazısı;
    public javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtGelenTc;
    // End of variables declaration//GEN-END:variables

}