/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Ali Asaf
 */
public class PolisEkranıSorgu extends javax.swing.JFrame {
    public Insan insan;
    Color old;
    
    
    /**
     * Creates new form PolisEkranıSorgu
     */
    public PolisEkranıSorgu() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }
    
     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconResmi.png"))); //To change body of generated methods, choose Tools | Templates.
    }
    
    public PolisEkranıSorgu(Insan insan){
     initComponents();
     setIcon();
     this.setLocationRelativeTo(null);
    this.insan=insan;
    
    
    EnterCinsiyet.setText(insan.Cinsiyet);
    EnterAnneAdı.setText(insan.AnneAdı);
    EnterBabaAdı.setText(insan.BabaAdı);
    EnterDoğumYeri.setText(insan.DoğumYeri);
    EnterDogumTarihi.setText(insan.DoğumTarih);
    EnterSoyİsim.setText(insan.Soyİsim);
    Enterİsim.setText(insan.İsim);
    EnterTcNo.setText(insan.TcNo);
    
    if(insan.CezaiDurum.compareTo("Serbest")==0){
        CBSerbest.setSelected(true);
        CBSerbest.setEnabled(false);
        CBDenetimliSerbest.setEnabled(false);
         CBAranıyor.setEnabled(false);
         
    }else if(insan.CezaiDurum.compareTo("Denetimli Serbest")==0){
        CBDenetimliSerbest.setSelected(true);
        CBSerbest.setEnabled(false);
        CBDenetimliSerbest.setEnabled(false);
         CBAranıyor.setEnabled(false);
    }else if(insan.CezaiDurum.compareTo("Aranıyor")==0){
        CBAranıyor.setSelected(true);
        CBSerbest.setEnabled(false);
        CBDenetimliSerbest.setEnabled(false);
         CBAranıyor.setEnabled(false);
    }
    
    if(insan.SabıkaKaydı1==null){
        EnterSabıka1.setText("Sabıkası Yoktur.");
    }
    else{
        EnterSabıka1.setText(insan.SabıkaKaydı1);
        EnterSabıkaTarih1.setText(insan.SabıkaKaydıTarih1);
    }
    
    if(insan.SabıkaKaydı2!=null){
        EnterSabıka2.setText(insan.SabıkaKaydı2);
        EnterSabıkaTarih2.setText(insan.SabıkaKaydıTarih2);
    }
     if(insan.SabıkaKaydı3!=null){
        EnterSabıka3.setText(insan.SabıkaKaydı3);
        EnterSabıkaTarih3.setText(insan.SabıkaKaydıTarih3);
    }
      if(insan.SabıkaKaydı4!=null){
        EnterSabıka4.setText(insan.SabıkaKaydı4);
        EnterSabıkaTarih4.setText(insan.SabıkaKaydıTarih4);
    }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPolisEkranıSorgu = new javax.swing.JPanel();
        lblSabıkaYazısı = new javax.swing.JLabel();
        lblİsim = new javax.swing.JLabel();
        lblSoyisim = new javax.swing.JLabel();
        lblTcNo = new javax.swing.JLabel();
        lblDogumTarihi = new javax.swing.JLabel();
        lblAnneAdı = new javax.swing.JLabel();
        lblCinsiyet = new javax.swing.JLabel();
        lblCezaiDurum = new javax.swing.JLabel();
        CBSerbest = new javax.swing.JCheckBox();
        CBDenetimliSerbest = new javax.swing.JCheckBox();
        CBAranıyor = new javax.swing.JCheckBox();
        Enterİsim = new javax.swing.JLabel();
        EnterSoyİsim = new javax.swing.JLabel();
        EnterTcNo = new javax.swing.JLabel();
        EnterDogumTarihi = new javax.swing.JLabel();
        EnterAnneAdı = new javax.swing.JLabel();
        EnterCinsiyet = new javax.swing.JLabel();
        btnTamam = new javax.swing.JButton();
        lblBabaAdı = new javax.swing.JLabel();
        lblDoğumYeri = new javax.swing.JLabel();
        EnterBabaAdı = new javax.swing.JLabel();
        EnterDoğumYeri = new javax.swing.JLabel();
        lblSabıkaBilgileri = new javax.swing.JLabel();
        EnterSabıka1 = new javax.swing.JLabel();
        EnterSabıkaTarih1 = new javax.swing.JLabel();
        EnterSabıka2 = new javax.swing.JLabel();
        EnterSabıka3 = new javax.swing.JLabel();
        EnterSabıka4 = new javax.swing.JLabel();
        EnterSabıka5 = new javax.swing.JLabel();
        EnterSabıkaTarih2 = new javax.swing.JLabel();
        EnterSabıkaTarih3 = new javax.swing.JLabel();
        EnterSabıkaTarih4 = new javax.swing.JLabel();
        EnterSabıkaTarih5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPolisEkranıSorgu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        lblSabıkaYazısı.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSabıkaYazısı.setText("Sabıka Kaydı Sorgulama Sistemi");

        lblİsim.setForeground(new java.awt.Color(0, 102, 0));
        lblİsim.setText("İsim :");

        lblSoyisim.setForeground(new java.awt.Color(0, 102, 0));
        lblSoyisim.setText("Soyisim :");

        lblTcNo.setForeground(new java.awt.Color(0, 102, 0));
        lblTcNo.setText("Tc No :");

        lblDogumTarihi.setForeground(new java.awt.Color(0, 102, 0));
        lblDogumTarihi.setText("Doğum Tarihi :");

        lblAnneAdı.setForeground(new java.awt.Color(0, 102, 0));
        lblAnneAdı.setText("Anne Adı :");

        lblCinsiyet.setForeground(new java.awt.Color(0, 102, 0));
        lblCinsiyet.setText("Cinsiyet :");

        lblCezaiDurum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCezaiDurum.setForeground(new java.awt.Color(51, 102, 0));
        lblCezaiDurum.setText("Cezai Durum :");

        CBSerbest.setText("Serbest");
        CBSerbest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CBSerbest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSerbestActionPerformed(evt);
            }
        });

        CBDenetimliSerbest.setText("Denetimli Serbest");

        CBAranıyor.setText("Aranıyor");

        Enterİsim.setForeground(new java.awt.Color(51, 51, 51));

        btnTamam.setText("Tamam");
        btnTamam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        btnTamam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTamamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTamamMouseExited(evt);
            }
        });
        btnTamam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamamActionPerformed(evt);
            }
        });

        lblBabaAdı.setForeground(new java.awt.Color(0, 102, 0));
        lblBabaAdı.setText("Baba Adı :");

        lblDoğumYeri.setForeground(new java.awt.Color(0, 102, 0));
        lblDoğumYeri.setText("Doğum Yeri :");

        lblSabıkaBilgileri.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSabıkaBilgileri.setForeground(new java.awt.Color(51, 102, 0));
        lblSabıkaBilgileri.setText("Sabıka Bilgileri:");

        javax.swing.GroupLayout pnlPolisEkranıSorguLayout = new javax.swing.GroupLayout(pnlPolisEkranıSorgu);
        pnlPolisEkranıSorgu.setLayout(pnlPolisEkranıSorguLayout);
        pnlPolisEkranıSorguLayout.setHorizontalGroup(
            pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDoğumYeri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(lblCinsiyet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBabaAdı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAnneAdı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnterCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterDoğumYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                                                .addComponent(EnterAnneAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(EnterSabıka5, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                    .addComponent(EnterSabıka4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(EnterBabaAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EnterSabıkaTarih4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EnterSabıkaTarih5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(CBSerbest)
                            .addComponent(CBDenetimliSerbest)
                            .addComponent(lblCezaiDurum)
                            .addComponent(CBAranıyor)
                            .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblİsim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSoyisim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTcNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDogumTarihi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Enterİsim, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterSoyİsim, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterDogumTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSabıkaBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(EnterSabıka3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(EnterSabıka2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EnterSabıka1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(EnterSabıkaTarih1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EnterSabıkaTarih2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EnterSabıkaTarih3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPolisEkranıSorguLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTamam, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        pnlPolisEkranıSorguLayout.setVerticalGroup(
            pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSabıkaYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSabıkaBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Enterİsim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblİsim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EnterSabıka1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnterSabıkaTarih1))
                    .addComponent(EnterSoyİsim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSoyisim, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EnterSabıka2)
                        .addComponent(EnterSabıkaTarih2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EnterDogumTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDogumTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                    .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EnterSabıka3)
                        .addComponent(EnterSabıkaTarih3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnneAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterAnneAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBabaAdı, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(EnterBabaAdı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDoğumYeri, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(EnterDoğumYeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterCinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(lblCezaiDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(CBSerbest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBDenetimliSerbest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBAranıyor)
                        .addGap(15, 15, 15)
                        .addComponent(btnTamam, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPolisEkranıSorguLayout.createSequentialGroup()
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EnterSabıka4)
                            .addComponent(EnterSabıkaTarih4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPolisEkranıSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EnterSabıka5)
                            .addComponent(EnterSabıkaTarih5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPolisEkranıSorgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPolisEkranıSorgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBSerbestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSerbestActionPerformed
 
    }//GEN-LAST:event_CBSerbestActionPerformed

    private void btnTamamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamamActionPerformed
    
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTamamActionPerformed

    private void btnTamamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTamamMouseEntered
      old=btnTamam.getForeground();
      btnTamam.setForeground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_btnTamamMouseEntered

    private void btnTamamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTamamMouseExited
      btnTamam.setForeground(old);  // TODO add your handling code here:
    }//GEN-LAST:event_btnTamamMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolisEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolisEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolisEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolisEkranıSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolisEkranıSorgu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBAranıyor;
    private javax.swing.JCheckBox CBDenetimliSerbest;
    private javax.swing.JCheckBox CBSerbest;
    private javax.swing.JLabel EnterAnneAdı;
    private javax.swing.JLabel EnterBabaAdı;
    private javax.swing.JLabel EnterCinsiyet;
    private javax.swing.JLabel EnterDogumTarihi;
    private javax.swing.JLabel EnterDoğumYeri;
    private javax.swing.JLabel EnterSabıka1;
    private javax.swing.JLabel EnterSabıka2;
    private javax.swing.JLabel EnterSabıka3;
    private javax.swing.JLabel EnterSabıka4;
    private javax.swing.JLabel EnterSabıka5;
    private javax.swing.JLabel EnterSabıkaTarih1;
    private javax.swing.JLabel EnterSabıkaTarih2;
    private javax.swing.JLabel EnterSabıkaTarih3;
    private javax.swing.JLabel EnterSabıkaTarih4;
    private javax.swing.JLabel EnterSabıkaTarih5;
    private javax.swing.JLabel EnterSoyİsim;
    private javax.swing.JLabel EnterTcNo;
    private javax.swing.JLabel Enterİsim;
    private javax.swing.JButton btnTamam;
    private javax.swing.JLabel lblAnneAdı;
    private javax.swing.JLabel lblBabaAdı;
    private javax.swing.JLabel lblCezaiDurum;
    private javax.swing.JLabel lblCinsiyet;
    private javax.swing.JLabel lblDogumTarihi;
    private javax.swing.JLabel lblDoğumYeri;
    private javax.swing.JLabel lblSabıkaBilgileri;
    private javax.swing.JLabel lblSabıkaYazısı;
    private javax.swing.JLabel lblSoyisim;
    private javax.swing.JLabel lblTcNo;
    private javax.swing.JLabel lblİsim;
    private javax.swing.JPanel pnlPolisEkranıSorgu;
    // End of variables declaration//GEN-END:variables
}
